CREATE TABLE IF NOT EXISTS llm_jobs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  job_id VARCHAR(32) NOT NULL UNIQUE,
  prompt TEXT NOT NULL,
  result_text LONGTEXT,
  status ENUM('PENDING', 'DONE', 'FAILED') DEFAULT 'PENDING',
  error_message TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
